package com.jonathan.xgithubapi.fragment

import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithContentDescription
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import com.jonathan.xgithubapi.ui.fragment.HomeFragment
import com.jonathan.xgithubapi.ui.model.EventState
import com.jonathan.xgithubapi.ui.model.GithubUi
import com.jonathan.xgithubapi.ui.theme.XGithubApiTheme
import io.mockk.mockk
import io.mockk.verify
import org.junit.Rule
import org.junit.Test

/**
 * Android uit test generated by UI
 */

@OptIn(ExperimentalMaterial3Api::class)
class HomeFragmentTest {

    @get:Rule
    val composeTestRule = createComposeRule()

    // ─── helpers ────────────────────────────────────────────────────────────────

    private fun makeRepo(
        name: String = "Jetpack Compose",
        ownerName: String = "Google"
    ) = GithubUi(
        name = name,
        avatar = "https://avatars.githubusercontent.com/u/1?v=4",
        description = "A modern UI toolkit",
        stars = 100,
        forks = 50,
        lastUpdated = "2025-01-01",
        language = "Kotlin",
        license = "Apache-2.0",
        ownerName = ownerName,
        ownerInfo = "owner info",
        fork = false
    )

    private fun setHomeFragment(
        eventState: EventState?,
        clickListener: (GithubUi) -> Unit = {},
        loadNextPage: () -> Unit = {},
        onRefresh: () -> Unit = {}
    ) {
        composeTestRule.setContent {
            XGithubApiTheme {
                HomeFragment(
                    eventState = eventState,
                    clickListener = clickListener,
                    loadNextPage = loadNextPage,
                    onRefresh = onRefresh
                )
            }
        }
    }

    // ─── toolbar ────────────────────────────────────────────────────────────────

    @Test
    fun toolbar_isAlwaysDisplayed() {
        setHomeFragment(eventState = EventState.Loading)
        composeTestRule.onNodeWithText("Github Repositories").assertIsDisplayed()
    }

    // ─── error state ─────────────────────────────────────────────────────────────

    @Test
    fun errorState_showsErrorMessage() {
        setHomeFragment(eventState = EventState.Error("Network error"))
        composeTestRule.onNodeWithText("Network error").assertIsDisplayed()
    }

    @Test
    fun errorState_showsErrorContentDescription() {
        setHomeFragment(eventState = EventState.Error("Something went wrong"))
        composeTestRule.onNodeWithContentDescription("Error").assertIsDisplayed()
    }

    // ─── repos state ─────────────────────────────────────────────────────────────

    @Test
    fun reposState_showsRepoName() {
        val repos = listOf(makeRepo(name = "Jetpack Compose"))
        setHomeFragment(eventState = EventState.Repos(repositories = repos))
        composeTestRule.onNodeWithText("Jetpack Compose").assertIsDisplayed()
    }

    @Test
    fun reposState_showsMultipleRepos() {
        val repos = listOf(
            makeRepo(name = "Repo One", ownerName = "OwnerA"),
            makeRepo(name = "Repo Two", ownerName = "OwnerB"),
            makeRepo(name = "Repo Three", ownerName = "OwnerC")
        )
        setHomeFragment(eventState = EventState.Repos(repositories = repos))
        composeTestRule.onNodeWithText("Repo One").assertIsDisplayed()
        composeTestRule.onNodeWithText("Repo Two").assertIsDisplayed()
        composeTestRule.onNodeWithText("Repo Three").assertIsDisplayed()
    }

    @Test
    fun reposState_clickOnCard_invokesClickListener() {
        val repo = makeRepo(name = "ClickableRepo", ownerName = "OwnerX")
        val clickListener = mockk<(GithubUi) -> Unit>(relaxed = true)

        setHomeFragment(
            eventState = EventState.Repos(repositories = listOf(repo)),
            clickListener = clickListener
        )

        composeTestRule.onNodeWithText("ClickableRepo").performClick()
        verify { clickListener.invoke(repo) }
    }


    @Test
    fun reposState_nextPageError_showsErrorBanner() {
        val repos = listOf(makeRepo(name = "Repo B", ownerName = "Owner2"))
        setHomeFragment(
            eventState = EventState.Repos(
                repositories = repos,
                isLoadingNextPage = false,
                nextPageError = "Failed to load more"
            )
        )
        composeTestRule.onNodeWithText("Repo B").assertIsDisplayed()
        composeTestRule.onNodeWithText("Failed to load more").assertIsDisplayed()
    }

    // ─── null / unknown state ────────────────────────────────────────────────────

    @Test
    fun nullState_showsUnknownStateError() {
        setHomeFragment(eventState = null)
        composeTestRule.onNodeWithText("Unknown state").assertIsDisplayed()
    }
}